import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "rahat-api/rahat-core",
    },
    {
      type: "category",
      label: "App",
      items: [
        {
          type: "doc",
          id: "rahat-api/app-controller-list-auth-apps",
          label: "AppController_listAuthApps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/app-controller-create-auth-app",
          label: "AppController_createAuthApp",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/app-controller-get-auth-app",
          label: "AppController_getAuthApp",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/app-controller-update-auth-app",
          label: "AppController_updateAuthApp",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rahat-api/app-controller-soft-delete-auth-app",
          label: "AppController_softDeleteAuthApp",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rahat-api/app-controller-get-by-address",
          label: "AppController_getByAddress",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Beneficiaries",
      items: [
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-list",
          label: "BeneficiaryController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-create",
          label: "BeneficiaryController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-list-temp-benef",
          label: "BeneficiaryController_listTempBenef",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-list-temp-groups",
          label: "BeneficiaryController_listTempGroups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-list-pii-data",
          label: "BeneficiaryController_listPiiData",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-get-stats",
          label: "BeneficiaryController_getStats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-get-stats-source",
          label: "BeneficiaryController_getStatsSource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-get-table-stats",
          label: "BeneficiaryController_getTableStats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-refer-beneficiary",
          label: "BeneficiaryController_referBeneficiary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-create-bulk",
          label: "BeneficiaryController_createBulk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-upload",
          label: "BeneficiaryController_upload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-upload-with-queue",
          label: "BeneficiaryController_uploadWithQueue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-update",
          label: "BeneficiaryController_update",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-delete",
          label: "BeneficiaryController_delete",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-get-beneficiary",
          label: "BeneficiaryController_getBeneficiary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-remove",
          label: "BeneficiaryController_remove",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-get-beneficiary-by-wallet",
          label: "BeneficiaryController_getBeneficiaryByWallet",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-get-beneficiary-by-phone",
          label: "BeneficiaryController_getBeneficiaryByPhone",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-generate-verification-link",
          label: "BeneficiaryController_generateVerificationLink",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-validate-wallet",
          label: "BeneficiaryController_validateWallet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-verify-signature",
          label: "BeneficiaryController_verifySignature",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-create-group",
          label: "BeneficiaryController_createGroup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-get-all-groups",
          label: "BeneficiaryController_getAllGroups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-get-one-group",
          label: "BeneficiaryController_getOneGroup",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-remove-group",
          label: "BeneficiaryController_removeGroup",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-update-group",
          label: "BeneficiaryController_updateGroup",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-group-account-check",
          label: "BeneficiaryController_groupAccountCheck",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-get-group-beneficiaries-failed-account",
          label: "BeneficiaryController_getGroupBeneficiariesFailedAccount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-add-group-purpose",
          label: "BeneficiaryController_addGroupPurpose",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-import-beneficiaries-from-tool",
          label: "BeneficiaryController_importBeneficiariesFromTool",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/beneficiary-controller-import-temp-beneficiaries",
          label: "BeneficiaryController_importTempBeneficiaries",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Settings",
      items: [
        {
          type: "doc",
          id: "rahat-api/settings-controller-list",
          label: "SettingsController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/settings-controller-create",
          label: "SettingsController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/settings-controller-get",
          label: "SettingsController_get",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/settings-controller-udpdate",
          label: "SettingsController_udpdate",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      items: [
        {
          type: "doc",
          id: "rahat-api/custom-users-controller-get-wallets",
          label: "CustomUsersController_getWallets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/users-controller-list",
          label: "UsersController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/users-controller-create",
          label: "UsersController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/users-controller-get-me",
          label: "UsersController_getMe",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/users-controller-update-me",
          label: "UsersController_updateMe",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/users-controller-change-password",
          label: "UsersController_changePassword",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/users-controller-get",
          label: "UsersController_get",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/users-controller-update",
          label: "UsersController_update",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/users-controller-delete",
          label: "UsersController_delete",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rahat-api/users-controller-get-roles",
          label: "UsersController_getRoles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/users-controller-add-roles",
          label: "UsersController_addRoles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/users-controller-remove-roles",
          label: "UsersController_removeRoles",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Vendors",
      items: [
        {
          type: "doc",
          id: "rahat-api/vendors-controller-register-vendor",
          label: "VendorsController_registerVendor",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/vendors-controller-list-vendor",
          label: "VendorsController_listVendor",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/vendors-controller-get-vendor-count",
          label: "VendorsController_getVendorCount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/vendors-controller-get-vendor",
          label: "VendorsController_getVendor",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/vendors-controller-get-otp",
          label: "VendorsController_getOtp",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/vendors-controller-verify-otp",
          label: "VendorsController_verifyOtp",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/vendors-controller-update-vendor",
          label: "VendorsController_updateVendor",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/vendors-controller-remove-vendor",
          label: "VendorsController_removeVendor",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Auth",
      items: [
        {
          type: "doc",
          id: "rahat-api/auths-controller-login-otp",
          label: "AuthsController_loginOtp",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/auths-controller-get-otp",
          label: "AuthsController_getOtp",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/auths-controller-wallet-login",
          label: "AuthsController_walletLogin",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/auths-controller-get-challenge",
          label: "AuthsController_getChallenge",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Roles & Permissions",
      items: [
        {
          type: "doc",
          id: "rahat-api/roles-controller-create-role",
          label: "RolesController_createRole",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/roles-controller-list-roles",
          label: "RolesController_listRoles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/roles-controller-search-roles-by-permission",
          label: "RolesController_searchRolesByPermission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/roles-controller-update-role",
          label: "RolesController_updateRole",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/roles-controller-delete-role",
          label: "RolesController_deleteRole",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rahat-api/roles-controller-get-role",
          label: "RolesController_getRole",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/roles-controller-list-perms-by-role",
          label: "RolesController_listPermsByRole",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Projects",
      items: [
        {
          type: "doc",
          id: "rahat-api/project-controller-create",
          label: "ProjectController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-list",
          label: "ProjectController_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-ms-actions",
          label: "ProjectController_msActions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-upload",
          label: "ProjectController_upload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-find-one",
          label: "ProjectController_findOne",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-update",
          label: "ProjectController_update",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-remove",
          label: "ProjectController_remove",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-update-status",
          label: "ProjectController_updateStatus",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-list-beneficiaries",
          label: "ProjectController_listBeneficiaries",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-add-settings",
          label: "ProjectController_addSettings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-project-actions",
          label: "ProjectController_projectActions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-project-stats",
          label: "ProjectController_projectStats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-project-stats-sources",
          label: "ProjectController_projectStatsSources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-import-from-kobo",
          label: "ProjectController_importFromKobo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-test-msg",
          label: "ProjectController_testMsg",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/project-controller-kobo-import-simulate",
          label: "ProjectController_koboImportSimulate",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Stats",
      items: [
        {
          type: "doc",
          id: "rahat-api/stats-controller-find-all",
          label: "StatsController_findAll",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/stats-controller-find-one",
          label: "StatsController_findOne",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Upload",
      items: [
        {
          type: "doc",
          id: "rahat-api/upload-controller-upload-file",
          label: "UploadController_uploadFile",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Grievances",
      items: [
        {
          type: "doc",
          id: "rahat-api/grievance-controller-create",
          label: "GrievanceController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/grievance-controller-find-all",
          label: "GrievanceController_findAll",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/grievance-controller-change-status",
          label: "GrievanceController_changeStatus",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "rahat-api/grievance-controller-soft-delete",
          label: "GrievanceController_softDelete",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Tokens",
      items: [
        {
          type: "doc",
          id: "rahat-api/token-controller-create",
          label: "TokenController_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/token-controller-find-all",
          label: "TokenController_findAll",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/token-controller-find-one",
          label: "TokenController_findOne",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/token-controller-remove",
          label: "TokenController_remove",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Offramps",
      items: [
        {
          type: "doc",
          id: "rahat-api/offramp-controller-create-offramp-request",
          label: "OfframpController_createOfframpRequest",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/offramp-controller-find-all-offramp-requests",
          label: "OfframpController_findAllOfframpRequests",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/offramp-controller-execute-offramp-request",
          label: "OfframpController_executeOfframpRequest",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/offramp-controller-register-provider",
          label: "OfframpController_registerProvider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/offramp-controller-list-providers",
          label: "OfframpController_listProviders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/offramp-controller-get-providers-by-id",
          label: "OfframpController_getProvidersById",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/offramp-controller-provider-actions",
          label: "OfframpController_providerActions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rahat-api/offramp-controller-find-one",
          label: "OfframpController_findOne",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Queue",
      items: [
        {
          type: "doc",
          id: "rahat-api/queue-controller-get-pending-contract-jobs",
          label: "Get Pending Contract Jobs with Filters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/queue-controller-retry-contract-job",
          label: "Retry a Failed Contract Job",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/queue-controller-get-pending-rahat-jobs",
          label: "Get Pending Rahat Jobs with Filters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/queue-controller-retry-rahat-job",
          label: "Retry a Failed Rahat Job",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/queue-controller-get-pending-rahat-beneficiary-jobs",
          label: "Get Pending Rahat Beneficiary Jobs with Filters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/queue-controller-retry-rahat-beneficiary-job",
          label: "Retry a Failed Rahat Beneficiary Job",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/queue-controller-get-pending-meta-txn-jobs",
          label: "Get Pending Meta Transaction Jobs with Filters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rahat-api/queue-controller-retry-meta-txn-job",
          label: "Retry a Failed Meta Transaction Job",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
